# Generated by Django 6.0.1 on 2026-01-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_campaign_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("is_subscribed", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="campaign",
            name="recipients",
            field=models.ManyToManyField(blank=True, to="myapp.recipient"),
        ),
    ]
