# Generated by Django 6.0.1 on 2026-01-27 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_recipient_campaign_recipients"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignlog",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.recipient",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaignlog",
            unique_together={("campaign", "recipient")},
        ),
    ]
