# Generated by Django 6.0.1 on 2026-01-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_campaignlog_recipient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignlog",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.recipient"
            ),
        ),
    ]
