# Generated by Django 6.0.1 on 2026-01-27 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_campaignlog_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignlog",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.recipient",
            ),
        ),
    ]
