# Generated by Django 6.0.1 on 2026-01-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_campaignlog_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
